// Generated by CoffeeScript 1.7.1
(function() {
  var docpadConfig;

  docpadConfig = {
    templateData: {
      site: {
        title: "My Website"
      },
      getPreparedTitle: function() {
        if (this.document.title) {
          return "" + this.document.title + " | " + this.site.title;
        } else {
          return this.site.title;
        }
      }
    },
    collections: {
      pages: function() {
        return this.getCollection("html").findAllLive({
          isPage: true
        });
      }
    }
  };

  module.exports = docpadConfig;

}).call(this);
